sudo: false

language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

before_install:
  - mvn clean

install:
  - mvn install -Dgpg.skip=true -DskipTests=true

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - bogdan.livadariu@gmail.com
