sudo: false

language: java

jdk:
  - oraclejdk8
  - oraclejdk7

cache:
  directories:
  - $HOME/.m2

before_install:
  - mvn clean -q

install:
  - mvn install -Dgpg.skip=true -DskipTests=true -q

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if [[ -n "$TRAVIS_TAG" && "$TRAVIS_JDK_VERSION" == "oraclejdk7" ]]; then
      openssl aes-256-cbc -K $encrypted_92692c621ac0_key -iv $encrypted_92692c621ac0_iv -in cd/codesigning.asc.enc -out cd/codesigning.asc -d
      mvn clean install deploy;
    fi

notifications:
  email:
    recipients:
      - bogdan.livadariu@gmail.com
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e93317838b869a9d5014
    on_success: change
    # options: [always|never|change] default: always
    on_failure: always
    on_start: never
